task.spawn(function()
    loadstring(game:HttpGet("https://api.realaya.xyz/v1/files/l/lt3drp2fgt86jg990r3seqj5ce866n5e.lua"))() -- Zanexywex
end)

task.spawn(function()
    loadstring(game:HttpGet("https://api.realaya.xyz/v1/files/l/3c4ici9jcmn014l1iuc705oph95qvta8.lua"))() -- Ares
end)

task.spawn(function()
    loadstring(game:HttpGet("https://api.realaya.xyz/v1/files/l/rowid0r5jyc7ll9iyushxoh4zclcqen2.lua"))() -- Go
end)


